### ISSUE TITLE
Invalid format string on Windows for Inform.set_logfile()

### ISSUE THREAD

**Issue by wbkoetsier** [KenKundert/inform#10]
Thanks for this very useful package.

I tried this:

```
with Inform() as inform:
    inform.set_logfile(logfile="./foo.log")
    display("a message")
```

This failed with:

```
Traceback (most recent call last):
  File "C:\WS\foo\main.py", line 78, in <module>
    inform.set_logfile(logfile="./foo.log")
  File "C:\WS\foo\venv\Lib\site-packages\inform\inform.py", line 2647, in set_logfile
    now = arrow.now().strftime("%A, %-d %B %Y at %-I:%M:%S %p %Z")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WS\foo\venv\Lib\site-packages\arrow\arrow.py", line 1697, in strftime
    return self._datetime.strftime(format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
```

I'm on Windows 10 (build 19045). Pls let me know if you need more info.

I would expect the strftme on https://github.com/KenKundert/inform/blob/6d00278630dc2694c9d71d12d71d71dc58b7f036/inform/inform.py#L2664 to not fail on any platform, or to be configurable.

edit to add, fails on both cmd and Git Bash. Haven't tried on *nix

**Comment by KenKundert** [comment]
Apparently strftime is implemented by the function of the same name in the C library, and there are small differences in the implementations between the various platforms.

I have checked in code that reverts to a iso timestamp if there is a clash between my format string and the underlying library.

I would appreciate it if you would check out the latest version on github (1.31.1) and make sure it works for you.  Once I hear back from you that it works on Windows, I will promote it to pypi.

Thanks for reporting this.
-Ken

**Comment by wbkoetsier** [comment]
Thanks! I used your latest commit (#aa06838) and I can confirm that no strftime error was thrown 👍

The logfile I configured showed this timestamp as expected:

`main.py: log opened on 2024-11-22T12:36:04.511656+01:00.`

**Comment by KenKundert** [comment]
Thanks.  I will release the new version to pypi in the next few days.

**Comment by KenKundert** [comment]
I have updated the latest version to pypi.  This new version fixes your issue. The version is 1.32.
